### ISSUE TITLE
Display preview of posts in Cells

### ISSUE THREAD

**Issue by bcye** [kgellci/Area51#10]
It would be great to show a preview of the post (either a link or the description) under the title of the table view cells.

This could be accomplished by using a cell preset with two labels.

**Comment by kgellci** [comment]
Could start by showing a text preview for Listings which have `selftext` set: https://github.com/reddit-archive/reddit/wiki/JSON#link-implements-votable--created

We could start with a generic TableViewCell with style `subtitle` for this purpose: https://developer.apple.com/documentation/uikit/uitableviewcell/cellstyle/subtitle

Or can make a totally new TableViewCell with a title and subtitle which would only be used to display Listings which have selftext.

We would need to parse out `selftext` and add as a property here: https://github.com/kgellci/Area51/blob/master/ListingService/Sources/Models/Listing.swift

Then we would need to populate the proper cell based on if there is or is not selftext here:
https://github.com/kgellci/Area51/blob/master/Area51/Sources/FeedViewController.swift

Is this something you would want to try implementing?

**Comment by bcye** [comment]
yes

**Comment by kgellci** [comment]
Should probably also set a limit to the number of lines for the subtitle, maybe something like 5.

**Comment by bcye** [comment]
I would aso suggest using Apple's Codable for parsing the JSON, it is much easier that way.

**Comment by kgellci** [comment]
https://github.com/kgellci/Area51/issues/16

**Comment by RJ-Clegg** [comment]
I’ll do this one.
