### ISSUE TITLE
[CoreAPI/Listing] Create "News" data for pulling data from /r/news

### ISSUE THREAD

**Issue by Sinbu** [kgellci/Area51#11]

**Comment by Sinbu** [comment]
Like other apps, this will enable quickly switching between popular and news. This is simply adding the option to the backend to be surfaced in the front-end (no design yet on the front-end). To accomplish this, I simply want to add a switch statement on the CoreAPI listing type, and add the proper API url for "r/news". In the future, we probably want to pull the list of possible subreddits they can select from in the front-end, and instead of doing a switch statement, allow the front-end component to inform the listing service which subreddits to fetch

**Comment by kgellci** [comment]
Sounds good!
