### ISSUE TITLE
Create board with tasks list

### ISSUE THREAD

**Issue by obozhdi** [kgellci/Area51#14]
Any possibility that we a have task list?

**Comment by kgellci** [comment]
Not sure if this helps, just set it up: https://github.com/kgellci/Area51/projects/1

**Comment by obozhdi** [comment]
Please gimme permission to add tasks there. I will make comprehensive list.

**Comment by kgellci** [comment]
I do not see a way to let someone manage the project without giving full ownership of all Area51. I set it up to automatically track issues. Adding a new issue should move it into the to-do section.  Does that work?

**Comment by RJ-Clegg** [comment]
Agreed a task list would be great. Will have a look at some solutions.

**Comment by kgellci** [comment]
@RJ-Clegg thanks for looking! I guess something where it is publicly visible and a subset of users can make changes would be 👍

**Comment by RJ-Clegg** [comment]
Having given this more thought; and not being able to use my favourite change management solution (JIRA) - I feel we should keep it as simple as possible. 

- Create a slack channel 
- Discuss what needs to be done and who wants to do what 
- Create issues on GitHub from those discussions. 

I mentioned this in this issue: https://github.com/kgellci/Area51/issues/26

Thoughts?

**Comment by kgellci** [comment]
Agree, I will setup slack

**Comment by kgellci** [comment]
@RJ-Clegg can you check if this allows you to sign up: https://join.slack.com/t/area51os/shared_invite/enQtNTE3NDM1NTc4NzcyLWZkMjkxMjA0ODA0ZTFjMTc4MzBmMjg3NDc4YjVmZjg0ZjI2MTkxOWE4YjAzNmU2ZTllMTBkZmUyZjU0OGM5OWI

**Comment by RJ-Clegg** [comment]
> @RJ-Clegg can you check if this allows you to sign up: https://join.slack.com/t/area51os/shared_invite/enQtNTE3NDM1NTc4NzcyLWZkMjkxMjA0ODA0ZTFjMTc4MzBmMjg3NDc4YjVmZjg0ZjI2MTkxOWE4YjAzNmU2ZTllMTBkZmUyZjU0OGM5OWI

Works just fine!

**Comment by RJ-Clegg** [comment]
Closing this. Slack channel up.
