### ISSUE TITLE
Create a CHANGELOG for the project

### ISSUE THREAD

**Issue by kgellci** [kgellci/Area51#17]
Would be cool to have a CHANGELOG where developers can list their changes. We can eventually display it in app as a what's new feed. It will also be useful for the Apple release notes when publishing to the store.

Here is the one from SwiftLint for reference: https://github.com/realm/SwiftLint/blob/master/CHANGELOG.md

We probably only need:
- Features
- Bug Fixes

**Comment by NickSet** [comment]
Is this referring to a static CHANGELOG.md file that contributors will manually update when they start a PR or something more automated?

**Comment by kgellci** [comment]
Static manual update. Something we can eventually show in the app as a what
has changed screen.
