### ISSUE TITLE
Add a TabBar as the root navigation

### ISSUE THREAD

**Issue by kgellci** [kgellci/Area51#22]
We should add a TabBarController with two tabs to start. 

- The first tab should hold the SplitViewController for the list of subreddits and feed. 
- The second tab should take you to a blank ViewController where we can turn it into a settings screen.

**Comment by kgellci** [comment]
I would recommend setting up the TabBarController in a new storyboard.

**Comment by mohitathwani** [comment]
I got this!

**Comment by kgellci** [comment]
Done here: https://github.com/kgellci/Area51/pull/34
