### ISSUE TITLE
Allow testing on a device without a Development team

### ISSUE THREAD

**Issue by karmatt** [kgellci/Area51#28]
I was thinking if we could allow testing on device without a development team?

**Comment by kgellci** [comment]
What happens if you try Xcodes fix issues? I probably need to setup an easy way to change the bundle id since it is registered to my account.

**Comment by RJ-Clegg** [comment]
Easy enough to sort out. @karmatt You can use your own dev account. Doesn't need to be a paid up membership. Change the bundle identifier and you'll be good to go.

**Comment by kgellci** [comment]
I can look into setting the bundleid to an ignored file so someone does not commit the change

**Comment by karmatt** [comment]
Thanks @RJ-Clegg and @kgellci. Should have realized to just change the bundleid

**Comment by RJ-Clegg** [comment]
> I can look into setting the bundleid to an ignored file so someone does not commit the change

Great idea - this would solve potential issues down the line.

**Comment by kgellci** [comment]
https://github.com/kgellci/Area51/pull/29

**Comment by kgellci** [comment]
@karmatt I’m going to close this out. Feel free to reopen if you still can’t or it is too difficult after the above changes

**Comment by karmatt** [comment]
@kgellci oops I forgot to close the issue. Thank you again!
