### ISSUE TITLE
Add a search bar to search subreddits

### ISSUE THREAD

**Issue by dulithadabare** [kgellci/Area51#44]
**Is your feature request related to a problem? Please describe.**
I would like to add a search bar to the subreddit view to search for subreddits.

**Describe the solution you'd like**
I would like add a search bar to filter default subreddits.

**Comment by kgellci** [comment]
Awesome! I would break this up into 3 separate features:
- Populate with default subreddits list (https://github.com/kgellci/Area51/issues/43)
- Add a search field which you can use to enter a custom subreddit and navigate to it
- Use some sort of search api from reddit to display results when typing into the search field

**Comment by Dulitha93** [comment]
Thanks. Shall I start working on populating with a list of default subreddits? (#43) ?

**Comment by dulithadabare** [comment]
I will start working on this

**Comment by dulithadabare** [comment]
Search bar added with some minor UI issues
