### ISSUE TITLE
[design] App Icon

### ISSUE THREAD

**Issue by kgellci** [kgellci/Area51#8]
We need an app icon else we can't distribute beta builds! 

Following [Apples HIG for icon design](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/) is the best place to start!

Appreciated files would be any of the following:

- .sketch
- .pdf
- 1024x1024 .png

**Comment by kgellci** [comment]
👍
Once you have a less abstract version, I think worth sharing to a design
community on Reddit for feedback!

**Comment by lucashoeft** [comment]
Here are my ideas for the app icon. There aren't final yet, so minor design tweaks have to be made if we decide for one of my drafts. We can still iterate over them (change background, add more colours, ...). Feedback is highly appreciated!

<img width="586" alt="screen shot 2019-01-05 at 10 19 27" src="https://user-images.githubusercontent.com/26332559/50722725-92e2ed00-10d3-11e9-8964-196b778432e9.png">

White Logo Version on Device

![logo white device](https://user-images.githubusercontent.com/26332559/50722732-befe6e00-10d3-11e9-994d-104c170dfb06.png)

Black Logo Version on Device

![logo black device](https://user-images.githubusercontent.com/26332559/50722736-c887d600-10d3-11e9-8a1b-89b11143ed07.png)

(I can send you the Sketch-File if we decide for one of the drafts)

**Comment by kgellci** [comment]
Can you try posting to https://www.reddit.com/r/design_critiques/ or https://www.reddit.com/r/UI_Design/

I personally like Wordmark white or black.

**Comment by lucashoeft** [comment]
Posted the screenshots to some subreddits and got little feedback:
- They liked overall style and design of the word mark and the alien with the antenna
- The word mark is missing the connection to reddit besides the used color

My thoughts on that: I'm not sure if I would like to have an icon with an alien on my home screen, because it does not look very friendly tbh. Maybe lets do something similar like an ufo. (I'll work on that)

**Comment by RJ-Clegg** [comment]
> Posted the screenshots to some subreddits and got little feedback:
> 
> * They liked overall style and design of the word mark and the alien with the antenna
> * The word mark is missing the connection to reddit besides the used color
> 
> My thoughts on that: I'm not sure if I would like to have an icon with an alien on my home screen, because it does not look very friendly tbh. Maybe lets do something similar like an ufo. (I'll work on that)

I concur on both points. A very good start though!

**Comment by kgellci** [comment]
Sounds good! Also, we can always refine the app icon over time so nbd if there is something less polished during beta.

**Comment by lucashoeft** [comment]
Here are some more ideas... I really like the ufo (no 10, no 17) over the alien, even though they are not the great for small sizes. To draw more attention and make the icon better looking for now, I would proceed with the word mark. Maybe later, when the app launching in the App Store, we can update the icon to make it more representative. If it is fine for you @kgellci @bcye @RJ-Clegg, I would add the word mark icon and create a pull request?

<img width="1440" alt="screen shot 2019-01-09 at 19 25 13" src="https://user-images.githubusercontent.com/26332559/50919889-56e9b800-1444-11e9-9b23-45b82b35fbf2.png">
<img width="1440" alt="screen shot 2019-01-09 at 19 25 22" src="https://user-images.githubusercontent.com/26332559/50919893-58b37b80-1444-11e9-88fc-fbb546bee21e.png">

**Comment by kgellci** [comment]
These are awesome! I kind of like the simplicity of 16. I also like the colors, on some of them. Can we try 16 in white with a gradient background of the salmonish color? Similar to the Airbnb icon

**Comment by lucashoeft** [comment]
Great to hear, what about this:

![icon](https://user-images.githubusercontent.com/26332559/51000286-e9658680-152c-11e9-8dd4-b8f85c847909.png)
![simulator screen shot - iphone xs - 2019-01-10 at 23 09 02](https://user-images.githubusercontent.com/26332559/51000300-f1bdc180-152c-11e9-9d56-f3e5c1505efb.png)

**Comment by kgellci** [comment]
Looks awesome! I think we should put it in. What is best for you to get it into the project?

You can make a PR with the .sketch file, maybe in the root directory under a folder called DesignResources, and I can merge and update the icons. You can also update the icons yourself as part of the PR if you want, everything is standard .xcasset

Or any other way which works for you, lmk.
