### ISSUE TITLE
UI Issue with UISearchBar in Landscape mode

### ISSUE THREAD

**Issue by dulithadabare** [kgellci/Area51#82]
**Describe the bug**
When  the Search Bar is focused in landscape mode, the top part of the search bar seems to be cutoff. Issue can be avoided by disabling the animation for moving the title of the view upwards. 
**To Reproduce**
1. Go to Subreddits view
2. Rotate device to landscape mode
3. Click on the Search Bar to focus on it and bring up the keyboard

**Expected behavior**
There should be a space between the edge of the screen and the Search Bar. The Search Bar should be completely visible
**Screenshots**
<img width="641" alt="screen shot 2019-02-25 at 8 09 06 pm" src="https://user-images.githubusercontent.com/12742157/53492117-0f83bd80-3abe-11e9-8a3e-2418e364540b.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - OS: iOS 12.1

**Additional context**
The issue can be avoided by disabling the UI animation which occurs when the Search Bar is focused.

**Comment by RJ-Clegg** [comment]
Since this seems to be an OS level bug and a rather minor one at that... closing this.
