### ISSUE TITLE
Add community icons for subreddits

### ISSUE THREAD

**Issue by dulithadabare** [kgellci/Area51#91]
**Describe the solution you'd like**
Add community icons to the subreddits displayed in the Subreddits VC. 
Community icon urls are available in the default subreddit listings.

**Additional context**
Icons can be added to the tableview cell as shown in the screenshot below

![redditscreen](https://user-images.githubusercontent.com/12742157/54139419-85394300-4447-11e9-8b4a-39903395b083.jpg)

**Comment by RJ-Clegg** [comment]
This is a great improvement. 
My only concern is the icons. Do they show that "+" as well or is that separate to the image?

**Comment by dulithadabare** [comment]
That is separate to the image.

**Comment by RJ-Clegg** [comment]
>That is separate to the image.

Okay great. Did you want to do this? ;)

**Comment by dulithadabare** [comment]
I took the screenshot from the reddit app and that + exists to subscribe to the subreddit. That will not be a part of the feature.

**Comment by RJ-Clegg** [comment]
>I took the screenshot from the reddit app and that + exists to subscribe to the subreddit. That will not be a part of the feature.

Yeah, that's clear. 👍
